blank_issues_enabled: false
contact_links:
  - name: ESP8266 Forum
    url: https://bbs.espressif.com/
    about: For questions about ESP8266
  - name: ESP32 Forum
    url: https://esp32.com
    about: For questions about ESP32
  - name: ESP IDF VSCode Extension Forum
    url: http://esp32.com/viewforum.php?f=40
    about: For questions about ESP-IDF VSCode Extensions
