name: Security Audit Dependencies

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check Node Packages Vulnerabilities
        run: yarn audit
